# Generated by Django 5.2.4 on 2025-08-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_dob_remove_user_email_remove_user_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
